apiVersion: batch/v1
kind: Job
metadata:
  name: add-logo-to-backend
  namespace: unstract
spec:
  template:
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: copy-logo
        image: busybox:1.36.1
        command: 
        - sh
        - -c
        - |
          echo "Creating logo.svg in backend pod..."
          cat > /tmp/logo.svg << 'EOF'
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 50">
            <text x="10" y="35" font-family="Arial, sans-serif" font-size="24" fill="#2F93F6">Henssler Financial</text>
          </svg>
          EOF
          echo "Logo created successfully"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "200m"
            ephemeral-storage: "200Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: backend-static
          mountPath: /tmp
      restartPolicy: Never
      volumes:
      - name: backend-static
        emptyDir: {}