#!/bin/bash
# Unstract Quick Access Guide

echo "=== Unstract Services Quick Access ==="
echo ""
echo "Main Application:"
echo "  URL: http://localhost:3000"
echo "  Login: unstract / unstract"
echo ""
echo "Quick Links:"
echo "  1. Main App:        http://localhost:3000"
echo "  2. API Docs:        http://localhost:8000/api/v1/docs"
echo "  3. MinIO Console:   http://localhost:9001 (minio/minio123)"
echo "  4. RabbitMQ:        http://localhost:15672 (admin/admin)"
echo "  5. Qdrant Vector:   http://localhost:6333/dashboard"
echo "  6. Traefik Routes:  http://localhost:8080"
echo "  7. Feature Flags:   http://localhost:8082"
echo ""
echo "To add new users:"
echo "  1. Login to the main app with default credentials"
echo "  2. Navigate to Settings > Users"
echo "  3. Click 'Add User' and fill in the details"
echo ""
echo "For detailed documentation, see: unstract-services-documentation.md"