apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: unstract
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unstract
      component: frontend
  template:
    metadata:
      labels:
        app: unstract
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ${ACR_LOGIN_SERVER}/unstract/frontend:IMAGE_TAG
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_BACKEND_URL
          value: "https://api.${INGRESS_HOST}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
