apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: unstract
    component: frontend
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: unstract
    component: frontend
  type: ClusterIP
