apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-service
  labels:
    app: unstract
    component: platform-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unstract
      component: platform-service
  template:
    metadata:
      labels:
        app: unstract
        component: platform-service
    spec:
      containers:
      - name: platform-service
        image: ${ACR_LOGIN_SERVER}/unstract/platform-service:IMAGE_TAG
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: unstract-config
        - secretRef:
            name: unstract-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
