apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: unstract
    component: postgresql
spec:
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    app: unstract
    component: postgresql
  type: ClusterIP
