apiVersion: v1
kind: Service
metadata:
  name: prompt-service
  labels:
    app: unstract
    component: prompt-service
spec:
  ports:
  - port: 5000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: unstract
    component: prompt-service
  type: ClusterIP
