apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: unstract
    component: rabbitmq
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 5672
    targetPort: amqp
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: unstract
    component: rabbitmq
  type: ClusterIP
