apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: unstract
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    app: unstract
    component: redis
  type: ClusterIP
