version: "3.9"
services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`frontend.unstract.localhost`) && !PathPrefix(`/api/v1`, `/deployment`)
      - traefik.http.services.frontend.loadbalancer.server.port=80
      - traefik.docker.network=unstract-network
